#!/usr/bin/python3
from sys import argv
from math import sqrt, ceil

if len(argv) != 2:
    raise Exception("Usage: ./factors FILENAME")

with open(argv[1], "r") as infile:
    for line in infile:
        number = int(line.strip())
        for i in range(2, ceil(sqrt(number))):
            if number % i == 0:
                print("{:d}={:d}*{:d}".format(number, number // i, i))
                break
